### ISSUE TITLE
For cron scripts data acquision, data conversion, and data storage should be in separate functions

### ISSUE THREAD

**Issue by cclauss** [giacomocerquone/UnivaqBot#12]
Moving `get_soup_from_url()` into utils helped to separate data acquisition and allowed us to remove a lot of redundant code.  Less code == less surface area for bugs.

The next step is to remove `utils.write_json()` function calls from the `scrape_xxx()` routines.  It will greatly aid testing and understandability if the `scrape_xxx(soup)` take in a soup (not a url) as a parameter and they return a dict (or list).  The production flow could become: `utils.write_json(scrape_xxx(utils.get_soup_from_url(url))` but writing does not belong inside the scraping function.

This way our functional tests can pass in soups and then make sure that the expected dictionary is returned by the function without having to write json data to the local filesystem.  This will also give us more flexibility to pick other destinations besides the local hard disk.  APIs for instance love to receive dicts, lists, etc.

**Comment by giacomocerquone** [comment]
We switched to mongodb, so I thought that for what we have now available, the wiser decision would be to completely forget about cron scripts or scraping stuff.
For info like professors, adsu, canteen and secretary we manually accumulate (or fastly create scrapers to accumulate) into mongo.
If we'll need truly constant scrapers, we'll think about it
