### ISSUE TITLE
What about adding a meteo/weather command?

### ISSUE THREAD

**Issue by cclauss** [giacomocerquone/UnivaqBot#15]
https://www.wunderground.com/weather/api/ or something similar could provide today's weather, 3 day forecast, etc.  500 API calls a day for `free` https://www.wunderground.com/weather/api/d/pricing.html

**Comment by giacomocerquone** [comment]
I personally don't like this idea. Let's know what @diegomariani thinks.

**Comment by ghost** [comment]
@cclauss Thanks for the interest, but a weather forecast notification service does not make any sense into the university bot
