### ISSUE TITLE
Avoid the change of sys.path to load python modules

### ISSUE THREAD

**Issue by giacomocerquone** [giacomocerquone/UnivaqBot#20]
We should discuss here how to avoid this kind of things we have right now in the code:

``` python
sys.path.insert(0, '../')
```

We're using this in news.py, for example, to load the utils module that is located in the parent folder.
I think should be avoided for two reason:
1. It breaks the linter since it doesn't resolve the path
2. For someone it's a bad practice and for [someone else](https://www.reddit.com/r/Python/comments/cmgbw/is_this_bad_practice_in_python_to_make_sure_i_can/) it's not. But honestly if we could find another simpler way, it would be good.

**Comment by cclauss** [comment]
I know of no other simpler way...  It is really more trouble than it is worth to change it.

When a project is small, it is best to keep all files in the same directory.  If you really want a multilayer package and you want _intra-package references_ you must always run your code as a package: `python -m UnivaqInfromaticaBot <option>`

See: https://docs.python.org/3/tutorial/modules.html#intra-package-references and http://www.dabeaz.com/modulepackage/

**Comment by giacomocerquone** [comment]
Well if so, I'd keep things like this.
