### ISSUE TITLE
the bot URL is broken.

### ISSUE THREAD

**Issue by giodegas** [giacomocerquone/UnivaqBot#28]
The link on the ReadMe goes to 404.
The [one](http://giacomocerquone.github.io/UnivaqBot) on the description still works:

    http://giacomocerquone.github.io/UnivaqBot/

**Comment by giacomocerquone** [comment]
Thanks :) fixed by https://github.com/giacomocerquone/UnivaqBot/commit/8e1c95b116fe0c5315fd90fc94db0ea5729ecfb8
